site_name: Campus Documentation
site_url: https://osg-htc.org/campus/
repo_name: campus
theme:
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.png

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OSGUserSchool
      name: OSG School on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OSGUserSchool
      name: OSG School on Facebook

nav:
  - Home:                           index.md
  - OSPool Contribution Requirements: ospool-requirements.md